---
filters:
- name: TODO
  query: "(due before: +0hours|overdue|no due date) & !#売却リスト& !#物欲 & !#作りたいものリスト & !#手が空いた時にやるリスト & !subtask"
- name: TODO - 職場
  query: "(due before: +0hours|overdue|no due date|today) & @職場  & !#売却リスト & !#物欲 & !#作りたいものリスト & !#手が空いた時にやるリスト & !subtask"
- name: TODO - 自宅
  query: "(due before: +0hours|overdue|no due date) & @自宅  & !#売却リスト & !#物欲 & !#作りたいものリスト"
